version: '3.8'

services:
  server:
    build: 
      context: ../server
      dockerfile: Dockerfile
    
    image: konzek-server
    expose:
      - 3000
    volumes:
      - ../server:/usr/src/app
    restart: always
    environment:
      - NODE_ENV=production
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - konzek-network
    
  
  nginx:
    image: nginx:latest
    container_name: konzek-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
    expose:
      - 80
    restart: always
    networks:
      - konzek-network

networks:
  konzek-network:
    driver: bridge
